sylius_grid:
    grids:
        lakion_cms_admin_route:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: "%lakion_cms.model.route.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                content:
                    type: twig
                    label: sylius.ui.content
                    options:
                        template: "@LakionCmsPlugin/Admin/Route/Grid/Field/content.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
