sylius_grid:
    grids:
        lakion_cms_admin_static_content:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: "%lakion_cms.model.static_content.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                title:
                    type: string
                    label: sylius.ui.title
            filters:
                title:
                    type: string
                    label: sylius.ui.title
                body:
                    type: string
                    label: sylius.ui.body
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
