imports:
    - { resource: "grids/custom_block.yml" }
    - { resource: "grids/product_block.yml" }
    - { resource: "grids/route.yml" }
    - { resource: "grids/static_content.yml" }
    - { resource: "grids/string_block.yml" }
    - { resource: "grids/taxon_block.yml" }

cmf_content:
    persistence:
        phpcr:
            content_basepath: /cms/pages

cmf_core:
    publish_workflow: true
    persistence:
        phpcr:
            enabled: true

cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
    dynamic:
        persistence:
            phpcr:
                enabled: true
                enable_initializer: true
                route_basepaths:
                    - /cms/routes

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms/content

sonata_block:
    default_contexts: [lakion_cms]

liip_imagine:
    filter_sets:
        cmf_block: ~
