lakion_cms_admin_route:
    resource: |
        alias: lakion_cms.route
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'update', 'delete']
        redirect: index
        grid: lakion_cms_admin_route
        permission: true
    type: sylius.resource

lakion_cms_admin_route_update:
    path: /routes/{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: lakion_cms.controller.route:updateAction
        _sylius:
            section: admin
            permission: true
            template: SyliusAdminBundle:Crud:update.html.twig
            vars:
                templates:
                    breadcrumb: "@LakionCmsPlugin/Admin/Route/Update/_breadcrumb.html.twig"
    requirements:
        id: ".+"

lakion_cms_admin_route_delete:
    path: /routes/{id}
    methods: [DELETE]
    defaults:
        _controller: lakion_cms.controller.route:deleteAction
        _sylius:
            section: admin
            permission: true
    requirements:
        id: ".+"
