lakion_cms_admin_static_content:
    resource: |
        alias: lakion_cms.static_content
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'update', 'delete']
        redirect: index
        grid: lakion_cms_admin_static_content
        vars:
            all:
                templates:
                    form: "@LakionCmsPlugin/Admin/StaticContent/_form.html.twig"
    type: sylius.resource

lakion_cms_admin_static_content_update:
    path: /static-contents/{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: lakion_cms.controller.static_content:updateAction
        _sylius:
            section: admin
            template: "@SyliusAdmin/Crud/update.html.twig"
            vars:
                templates:
                    form: "@LakionCmsPlugin/Admin/StaticContent/_form.html.twig"
                    breadcrumb: "@LakionCmsPlugin/Admin/StaticContent/Update/_breadcrumb.html.twig"
    requirements:
        id: ".+"

lakion_cms_admin_static_content_delete:
    path: /static-contents/{id}
    methods: [DELETE]
    defaults:
        _controller: lakion_cms.controller.static_content:deleteAction
        _sylius:
            section: admin
    requirements:
        id: ".+"
